### ISSUE TITLE
aztfy bug #2

### ISSUE THREAD

**Issue by H-Nawaz** [Azure/aztfy#65] opened 2022-04-14 09:40 UTC
The tool appears to create the subnets without defining the subnet address space within the subnet.

This in turn when attempting to use the TF code generates the following error.

AddressPrefixStringCannotBeNullOrEmpty

Haq

**Comment by magodo** [comment] 2022-04-15 01:57
@H-Nawaz This is caused by a mis-configuration in the AzureRM provider, which is tracked by https://github.com/hashicorp/terraform-provider-azurerm/pull/16402. Once it is merged, we can update the schema of the provider and fix this issue. Thank you for reporting this!

**Comment by koudaiii** [comment] 2022-04-25 08:24
https://github.com/hashicorp/terraform-provider-azurerm/pull/16402 and https://github.com/Azure/aztfy/pull/68 were recently merged.  Can this issue be closed in the next release of aztfy?

**Comment by magodo** [comment] 2022-04-25 08:49
Thank you @koudaiii for the update! I'll close this issue then. @H-Nawaz Please feel free to reopen if it still not working.

**Closed by magodo** 2022-04-25 08:49 UTC
Labels: bug, upstream-provider
