### ISSUE TITLE
aztfy Bug

### ISSUE THREAD

**Issue by H-Nawaz** [Azure/aztfy#64] opened 2022-04-14 09:13 UTC
when converting NSGs the argument protocol terraform expects to receive is case sensitive, however aztfy creates this in all upper case which causes terraform error as follows.

Error: expected protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP

Easy fix within the TF code to change to Tcp instead of TCP but just wanted to highlight this as a bug.

**Comment by magodo** [comment] 2022-04-14 09:50
@H-Nawaz Thank you for submitting this!

This is actually not a bug in `aztfy`, but an inconsistency between the provider behavior (only allows `Tcp` since v3.0) and the service behavior (case insensitive), which is trackedd in: https://github.com/hashicorp/terraform-provider-azurerm/issues/16092.

What `aztfy` does is simply call `terraform import` and convert the state to config. This means the `property` is set as `TCP` in the state after importing. This always indicates that in the remote platform, the `protocol` is set as `TCP`. So I assume after you manually change this to be `Tcp`, you'll hit a plan diff for it.

I'm going to close this issue as this is something needs to be fixed in the provider, for which you can track https://github.com/hashicorp/terraform-provider-azurerm/issues/16092 for any progress. Whilst, still thank you for submitting this!

**Closed by magodo** 2022-04-14 09:50 UTC
